### ISSUE TITLE
when to release the code

### ISSUE THREAD

**Issue by ryderling** [cdluminate/advrank#4]
Thanks a lot for this nice work!
Can I have the time or plan for the code releasing?
Looking forward to your reply and many thanks!

**Comment by cdluminate** [comment]
@kleincup Thank you for your interest. The code has to be polished before being released. I guess this can be finished before the ICLR deadline as long as I would have enough time for it :-)

**Comment by ryderling** [comment]
Thank you for your quick reply!
So the date will be after about 2 months?

**Comment by cdluminate** [comment]
@kleincup it depends on my workload, but I think yeah. It should be available in no more than 2 months.

**Comment by xunguangwang** [comment]
@cdluminate Hi! Do you consider implementing ranking attack under black-box setting without substitute model?

**Comment by cdluminate** [comment]
@xunguangwang Yes. I planned to devise black-box QA and CA without using transferability for the journal version.

**Comment by xunguangwang** [comment]
@cdluminate So, do you implemented the black box version?

**Comment by cdluminate** [comment]
The code has been released.

**Comment by cdluminate** [comment]
@xunguangwang The black-box version is work-in-progress.
